services:
  - type: web
    name: bcv-scraper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
